train:
  batch: 16
  lr: 1e-3
  device: 'cuda'
  total_epoch: 500
  workers: 8
  weight_decay: 0.05
  warmup_epoch: 20


vqvaemesh:
  num_embeddings: 512
  embedding_dim: 9
  commitment_cost: 0.25
  decay: 0.99
  num_quantizer: 1
  

modelconv:
  batch: 16
  connection_folder: body_models/ConnectionMatrices/
  initial_connection_fn: body_models/ConnectionMatrices/_pool0.npy
  connection_layer_lst: ["pool0", "pool1", "pool2","pool3", "pool4", "pool5", "pool6","unpool6", "unpool5","unpool4","unpool3","unpool2","unpool1", "unpool0"]
  channel_lst: [ 32, 32,  64, 64, 128, 128, 9, 128, 128,64, 64,32, 32,3]
  weight_num_lst: [9,0, 9,0, 9,0, 9,9, 0,9,0,9,0,9]
  residual_rate_lst: [0,1,  0,1,  0,1,  0,0,  1,0,  1,0,  1,0]
  
model:
  seq_length: 54
  emb_dim: 1024
  encoder_layer: 12
  encoder_head: 4
  decoder_layer: 4
  decoder_head: 4
  mask_ratio: 1
  num_embeddings: 512
  dim_tokens: 512
  masking: 'scheduled'
  
training_data:
  file: 'datasets/bedlam_animations'
  
validation_data:
  file: 'datasets/3DPW/3DPW_validation.npz'

test_data:
  file: '3DPW/3DPW_test.npz'
